### ISSUE TITLE
CC0 License

### ISSUE THREAD

**Issue by thodson-usgs** [sanjib-sen/WebLaTex#11]
Under MIT, am I "technically" required to include the MIT License on anything written using the WebLaTex template?
Nothing against MIT, but it seems awkward to inherent a license just for writing from this template.
Consider switching to CC0 License https://creativecommons.org/share-your-work/public-domain/cc0/

**Comment by sanjib-sen** [comment]
Creative Commons licenses are mostly applicable for Educational, Scientific resources, Public Domains, Datasets, Public Information, Health domains, etc. Considering this is Software, it does not fall upon these sectors.

Even Creative Commons does not recommend their licenses for Computer Software and Hardware.
![image](https://user-images.githubusercontent.com/54777542/231369704-825bdc4e-a353-4fb0-89b7-c20c603cb32f.png)
[Referring to this](https://creativecommons.org/faq/#:~:text=The%20only%20categories%20of%20works,otherwise%20in%20the%20public%20domain.).

Don't worry, MIT License is heavily used in the FOSS community and it does not restrict you to do anything with the Software, including monetization. And [it is on par with the CCO license except you have to include the original copyright and license notice.](https://www.slant.co/versus/3575/3578/~mit-license_vs_creative-commons)

**Comment by thodson-usgs** [comment]
Interesting. I wasn't aware of that recommendation. U.S. Federal government (my employer) requires the use CC0 for everything, software included, which, as you may imagine, is really annoying.

I'm not concerned about MIT per se, more that any document I edit in WebLaTex would(?) acquire a MIT license. Anyway, I don't want to go down a license rabbit hole, but I thought I'd raise the issue.

Thanks for investigating.

**Comment by sanjib-sen** [comment]
> I'm not concerned about MIT per se, more that any document I edit in WebLaTex would(?) acquire an MIT license.

No. It does not at all. WebLaTex is a tool. You will do your thing with this tool just like other tools and software. You can mention in your document that, This document is created by `WebLaTex` and you do not need to include any license or stuff. Treat WebLaTex just like you treat Microsoft Word, Google Docs, or Overleaf.

And in case you are still in confusion, this comment will act as a statement that I gave you permission to 'Not Include' the license on your Documents.
